Bugfix for restarting docker container.
When a previously stopped docker container is started again the following errors show up:
    yaml.composer.ComposerError: found duplicate anchor 'ttl'; first occurence
This is fixed by not appending to postgres.yml for the first entry, but by writing to it

The other issue is:
    fatal: destination path 'patroni' already exists and is not an empty directory
This is because git clone cannot clone into an already existing patroni directory
This is fixed by only executing git clone if the directory does not yet exist.